name: Release oidc-authorization-server-fake
on:
  release:
    types: [published]
env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  release:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Retag and push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: "${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}"
          dst: |
            "${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
            "${{ env.IMAGE_NAME }}:latest"
